version: '3.8'
services:
  db:
    build: ./docker/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: aiinfluencer
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
